Week 4 - Day 1 - Update mobile menu design of the portfolio
benjp009/benjamin-patin-portfolio-2021 pull request #12
Opened 2021-11-08 19:08 UTC by benjp009

2021-11-08 22:30 UTC, benjp009 commented on menu.js
> +// eslint-disable-next-line no-unused-vars
We couldn't find out how to fix the linter error `no-unused-vars`, so we added this line of code to pass the linters, if you have any idea why the linter failed, please do let us know, and we will fix it. :)

2021-11-08 23:02 UTC, de-scholar requested changes
Hi @benjp009 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-08 23:16 UTC, benjp009 commented on index.html
>          </div>
Thanks for your feedbacks @de-scholar 
I will work on the `x` button, actually it's already here on the page, but out of the screen view :) 
--
I will work on that and resubmit

2021-11-09 06:43 UTC, benjp009 commented
# 👋 Micronaut Reviewer 
## Second Review 

We have done all the changes required by the previous reviewer, including the optional once. I know the design of the page is not perfect, but it fits today requirements about mobile menu JavaScript requirements. 

- [x] The menu is missing the close `X` button to close it
- [ ] [optional] The menu should be full screen, please remove the white space at the very top of the menu bar
- [x] [ optional ]  The full screen version, looks buggy, the menu bar is occupying the whole screen, it would be nice if you implement it

### Thanks for taking the time to review my work :)

2021-11-09 06:50 UTC, Davidosky007 commented
## Hi @benjp009 👋, 

## Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 



![well-done](https://user-images.githubusercontent.com/52497246/140875937-a6f47893-2840-49ad-b67e-6bc7b3a5a8d5.jpg)
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-09 07:07 UTC, benjp009 commented
## Hi @Davidosky007 👋, 

#### Thank you so much for your review and approval !!! 

![Thanks](https://media.giphy.com/media/B231v18whPftXq6Na9/giphy.gif
)
Cheers and Happy coding!👏👏👏

2021-11-09 07:13 UTC, merged